config/routes.rb
Auth::Application.routes.draw do
  resources :global_settings
  resources :sessions do
    member do
      get 'new_admin'
      #get 'admin_destroy'
      #get 'create_admin'
    end
  end
  resources :password_resets

  resources :organizations do
    collection do
      get 'index_active_orgs'
    end
    member do
      get 'deactivate_account'
    end
    resources :settings
    resources :settings
    resources :users do
      member do
        get 'admin_login'
        get 'new_admin'
        get 'set_pin'
        get 'save_pin'
      end
    end
    resources :outstandings do
      collection do
        get 'expired_index'
      end
      member do
        get 'cancel_alert'
        get 'panic_alert'
        get 'sent_alert'
        get 'pin_cancel'
      end
      resources :checkins
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  get "org_index" => "organizations#index_active_orgs", :as => "org_index"
  #get "deactivate_account" => "organizations#deactivate_account", :as => "deactivate_account"
  #resources :organizations, :member => {:organizations => :index_active_orgs}
  #resources :organizations, :member => {:organizations => :deactivate_account}

  get "pin_cancel" => "organizations#outstandings#pin_cancel", :as => "pin_cancel"
  get "cancel_alert" => "organizations#outstandings#cancel_alert", :as => "cancel_alert"
  get "panic_alert" => "organizations#outstandings#panic_alert", :as => "panic_alert"
  get "sent_alert" => "organizations#outstandings#sent_alert", :as => "sent_alert"
  get "expired" => "organizations#outstandings#expired_index", :as => "expired"
  get "active" => "organizations#outstandings#index", :as => "active"
  get "new_alert" => "organizations#outstandings#new", :as => "new_alert"
  #resources :outstandings, :member => {:outstandings => :expired_index}
  #resources :outstandings, :member => {:outstandings => :cancel_alert}
  #resources :outstandings, :member => {:outstandings => :pin_cancel}
  #resources :outstandings, :member => {:outstandings => :panic_alert}
  #resources :outstandings, :member => {:outstandings => :sent_alert}
  #resources :outstandings, :member => {:outstandings => :index}


  get "admin_login" => "sessions#create", :as => "admin_login"
  get "admin" => "sessions#new_admin", :as => "admin"
  get "admin_logout" => "sessions#destroy", :as => "admin_logout"
  #get "admin_login" => "sessions#create_admin", :as => "admin_login"
  #get "admin" => "sessions#new_admin", :as => "admin"
  #get "admin_logout" => "sessions#admin_destroy", :as => "admin_logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "organizations#users#new", :as => "signup"
  get "set_pin" => "organizations#users#set_pin", :as => "set_pin"
  get "save_pin" => "organizations#users#save_pin", :as => "save_pin"
  #resources :users, :member => {:users => :set_pin}
  #resources :users, :member => {:users => :save_pin}
  #resources :sessions, :member => {:sessions => :new_admin}
  #resources :sessions, :member => {:sessions => :admin_destroy}
  #resources :sessions, :member => {:sessions => :create_admin}

  #if mobile_user?
    root :to => "sessions#new"
  #else
  #  root :to => "sessinons#new_admin"
  #end




end

app/controllers/outstandings_controller.rb
class OutstandingsController < ApplicationController
  before_filter :get_org
  before_filter :check_org, :only => :expired_index
  #before_filter :check_org, :only => :expired_index

  def get_org
    @organization = Organization.find(params[:organization_id])
  end

  def check_org
    if current_user.super_user != true
      @proper_org = Organization.find(current_user.organization)
    end

    #if current_user.admin != true && current_user.super_user != true
    #  redirect_to new_organization_outstanding_path(@proper_org)
    if @proper_org != @organization && current_user.super_user != true
      puts "wrong org"
      redirect_to organization_path(@proper_org)
    end
  end

  # GET /outstandings
  # GET /outstandings.json
  def index
    @outstandings = Outstanding.find(:all, :order => "panic_deadline DESC")


    respond_to do |format|
      format.html { render :layout => 'application_dashboard' }
      format.json { render json: @outstandings }
    end
  end

  # GET /outstandings
  # GET /outstandings.json
  def expired_index
    @outstandings = Outstanding.find(:all, :order => "panic_deadline DESC")
    respond_to do |format|
      format.html { render :layout => 'application_dashboard' }
      format.json { render json: @outstandings }
    end
  end

  # GET /outstandings/1
  # GET /outstandings/1.json
  def show
    @outstanding = Outstanding.find(params[:id])
    @user = User.find(@outstanding.user_id)


    respond_to do |format|
      format.html { render :layout => 'application_mobile_cnt' }
      format.json { render json: @outstanding }
    end
  end

  # GET /outstandings/new
  # GET /outstandings/new.json
  def new
    @outstanding = Outstanding.new
  #  my_user_id = current_user.id.to_i
  #  puts "Current User ID:" + current_user.id.to_i.to_s
  #  @user_assc_arr = UserToOutstAssc.where("user_id = ? AND active = ?", my_user_id, true)

  #  if @user_assc_arr.any?
  #    @user_assc = @user_assc_arr.last
  #    o_id = @user_assc.outstanding_id
  #
  #    @curr_outstanding = Outstanding.find(o_id)
    if current_user.active_outstanding
      @curr_outstanding = @organization.outstandings.find(current_user.active_outstanding)
      redirect_to organization_outstanding_path(@organization, @curr_outstanding)
    else
      respond_to do |format|
       format.html { render :layout => 'application_mobile_loc'}
        format.json { render json: @outstanding }
     end
    end
  end

  # GET /outstandings/1/edit
  def edit
    @outstanding = Outstanding.find(params[:id])
  end

  # POST /outstandings
  # POST /outstandings.json
  def create
    @outstanding = @organization.outstandings.new(params[:outstanding])
    @user = current_user
    @outstanding.user_id = @user.id

    respond_to do |format|
      if @outstanding.save
        format.html { redirect_to organization_outstanding_path(@organization, @outstanding), notice: 'Outstanding was successfully created.' }
        format.json { render json: @outstanding, status: :created, location: @outstanding }
      else
        format.html { render action: "new" }
        format.json { render json: @outstanding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outstandings/1
  # PUT /outstandings/1.json
  def update
    @outstanding = Outstanding.find(params[:id])

    respond_to do |format|
      if @outstanding.update_attributes(params[:outstanding])
        format.html { redirect_to organization_outstanding_path(@organization, @outstanding), notice: 'Outstanding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outstanding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outstandings/1
  # DELETE /outstandings/1.json
  def destroy
    @outstanding = Outstanding.find(params[:id])
    @outstanding.destroy

    respond_to do |format|
      format.html { redirect_to expired_path }
      format.json { head :no_content }
    end
  end

  def sent_alert
    put "Sent Alert"
    #@outstanding = Outstanding.find(params[:id])
    #@outstanding.sent_alert
    #outst_rel = OutstToJobRelation.find(@outstanding.id)
    #unless outst_rel.panic?
      render :layout => 'alert'
    #end
  end

  def panic_alert
    puts "Panic Alert"
    @outstanding = Outstanding.find(params[:id])
    @outstanding.panic_alert

    render :layout => 'alert'
  end

  def cancel_alert
    @outstanding = Outstanding.find(params[:id])
    @outstanding.cancel_alert
    if mobile_device?
      redirect_to new_organization_outstanding_path(@organization)
    else
      redirect_to organization_outstandings_path(@organization)
    end
  end

  def pin_cancel
    @outstanding = Outstanding.find(params[:id])
    render :layout => 'application_mobile_pin'
  end

end

app/helpers/outstandings_helper.rb
module OutstandingsHelper
end

app/views/outstandings/_checkins.html.erb
<h1>Listing checkins</h1>

<table>
  <tr>
    <th>Checkin Location</th>
    <th>Checkin time</th>
    <th>Added hours</th>
    <th>Added mins</th>
  </tr>

  <% @outstanding.checkins.each do |checkin| %>
      <% if @outstanding.panic_deadline_holding == checkin.checkin_time %>
          <tr>
            <td><a href="http://maps.google.com/maps?q=<%= checkin.latitude %>,<%= checkin.longitude %>">Google Map</a></td>
            <td>Original Alert</td>
            <td><%= checkin.checkin_hours %></td>
            <td><%= checkin.checkin_mins %></td>
          </tr>
      <% else %>
          <tr>
            <td><a href="http://maps.google.com/maps?q=<%= checkin.latitude %>,<%= checkin.longitude %>">Google Map</a></td>
            <td><%= checkin.checkin_time %></td>
            <td><%= checkin.checkin_hours %></td>
            <td><%= checkin.checkin_mins %></td>
          </tr>
      <% end %>
      
  <% end %>
</table>
<br />

app/views/outstandings/_form.html.erb
<section id="content">
  <!--start page contents-->
  <!-- area: clock readout -->
  <div class="checkin-counter">


    <%=  image_tag "webapp/clock/0.png", :id => "dig1" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig2" %>
    <%=  image_tag "webapp/clock/colon.png" %>
    <%=  image_tag "webapp/clock/3.png", :id => "dig3" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig4" %>
  </div>




  <!-- area: main -->
  <div id="whole" class="Main ColWhole">
    <div class="checkin-numpad">
      <form name="pin_pad">
        <input type="button" onclick="numKeys(1)" class="nbutton n1"/>
        <input type="button" onclick="numKeys(2)" class="nbutton n2"/>
        <input type="button" onclick="numKeys(3)" class="nbutton n3"/>
        <br />
        <input type="button" onclick="numKeys(4)" class="nbutton n4"/>
        <input type="button" onclick="numKeys(5)" class="nbutton n5"/>
        <input type="button" onclick="numKeys(6)" class="nbutton n6"/>
        <br />
        <input type="button" onclick="numKeys(7)" class="nbutton n7"/>
        <input type="button" onclick="numKeys(8)" class="nbutton n8"/>
        <input type="button" onclick="numKeys(9)" class="nbutton n9"/>
        <br />
        <input type="button" onclick="backspace()" class="nbutton n10"/>
        <input type="button" onclick="numKeys(0)" class="nbutton n11"/>
        <input type="button" onclick="clearPin()" class="nbutton n12">
        <br />
      </form>

      <div class="clr"></div>

    </div>
    <div class="clr"></div>
  </div>

  <div class="clr"></div>

  <!--end page contents-->
</section>
<div class="clr"></div>
<footer class="footer" id="footer">
  <div>
    <%= form_for([@organization, @outstanding]) do |f| %>


        <%= f.hidden_field :deadline_hours, :id => 'hours_field'   %>
        <%= f.hidden_field :deadline_mins,  :id => 'mins_field' %>
        <%= f.hidden_field :latitude, :id => "latitude" %>
        <%= f.hidden_field :longitude, :id => "longitude" %>
        <%= f.hidden_field :manual_panic, :value => false %>
        <div class="button-activate"><%= f.submit "  ", :class => "button-activate-hidden" %></div>
    <% end %>

  </div>
</footer>

app/views/outstandings/_form_update.html.erb
<%= form_for([@organization, @outstanding]) do |f| %>

  <div class="field">
    <%= f.select :deadline_hours, options_for_select(Array(0..99), 0)  %><%= f.label :deadline_hours %>
    <%= f.select :deadline_mins, options_for_select(Array(0..59), 0) %><%= f.label :deadline_mins %>
    <%= f.hidden_field :latitude, :id => "latitude" %>
    <%= f.hidden_field :longitude, :id => "longitude" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outstandings/edit.html.erb
<h1>Editing outstanding</h1>

<%= render 'form_update' %>

<%= link_to 'Show', @outstanding %> |
<%= link_to 'Back', outstandings_path %>

app/views/outstandings/expired_index.html.erb
<!-- area: main -->
<div id="whole" class="Main ColWhole">

  <!--generate user alerts table -->

  <table class="Table-UserAlert">
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Check Out Duration</th>
    <!--  <th>Extended Time</th>  -->
      <th>Time Expired</th>
      <th>Status</th>
      <th>Location on Record</th>
    <!--  <th></th> -->
      <th>Delete</th>
    </tr>
    


    <!-- start generated rows here -->
    <% @organization.outstandings.each do |outstanding| %>
        <% if outstanding.history_cutoff(@organization) %>
            <% outstanding.status_image(@organization) %>

            <tr>
              <% user = User.find_by_id(outstanding.user_id) %>
              <td><%= user.name_last %> &nbsp;</td>
              <td><%= user.name_first%> &nbsp;</td>
        <td><%= outstanding.deadline_hours %>:<%= outstanding.deadline_mins %>:00</td>
     <!--   <td>..:..:..</td>  -->
        <td><%= outstanding.panic_deadline %></td>
        <td>
          <img src="/assets/images/stoplight-red.jpg">
        </td>
        <td><a href="http://maps.google.com/maps?q=<%= outstanding.latitude  %>,<%= outstanding.longitude%>" target="_blank">Link to Map</a></td>
     <!--   <td><%= link_to 'Show', organization_outstanding_path(@organization, outstanding) %></td>  -->
        <td><%= link_to 'Destroy', organization_outstanding_path(@organization, outstanding), confirm: 'Are you sure?', method: :delete %></td>
        </tr>
            <% end %>
    <% end %>




    <!-- close user alerts table -->

  </table>

  <!-- end user alerts table -->


</div>
<div class="clr"></div>

app/views/outstandings/index.html.erb
<!-- area: main -->
<div id="whole" class="Main ColWhole">

  <!--generate user alerts table -->

  <table class="Table-UserAlert">
    <tr>
      <th>Last Name</th>
      <th>First Name</th>
      <th>Check Out Duration</th>
    <!--  <th>Extended Time</th>  -->
      <th>Time Remaining</th>
      <th>Status</th>
      <th>Location on Record</th>
    <!--  <th>Show</th>  -->
      <th>Delete</th>
    </tr>

    <!-- start generated rows here -->
    <% @organization.outstandings.each do |outstanding| %>

        <% outstanding.status_image(@organization) %>
        <% if outstanding.check_not_expired %>
            <tr>
              <% user = User.find_by_id(outstanding.user_id) %>
              <td><%= user.name_last %> &nbsp;</td>
              <td><%= user.name_first%> &nbsp;</td>

              <td><%= outstanding.deadline_hours %>:<%= outstanding.deadline_mins %>:00</td>
           <!--   <td>..:..:..</td>   -->
              <td>
                <% outstanding.time_remaining %>
                <%= outstanding.remaining_hours %> : <%= outstanding.remaining_mins %> : <%= outstanding.remaining_seconds %></td>
              <td>
                <img src="<%= outstanding.status %>">
              </td>
              <td>
                <a href="http://maps.google.com/maps?q=<%= outstanding.latitude  %>,<%= outstanding.longitude%>" target="_blank">Link to Map</a>
              </td>
           <!--   <td><%= link_to 'Show', organization_outstanding_path(@organization, outstanding) %></td>   -->
              <td><%= link_to 'Deactivate', cancel_alert_organization_outstanding_path(@organization, outstanding) %></td>
            </tr>
        <% end %>
     <% end %>




    <!-- close user alerts table -->

  </table>

  <!-- end user alerts table -->


</div>
<div class="clr"></div>

app/views/outstandings/new.html.erb
<%= render 'form' %>

app/views/outstandings/panic_alert.html.erb
<%= link_to image_tag("webapp/buttons/home.jpg"), new_organization_outstanding_path(@organization) %> </div>

app/views/outstandings/pin_cancel.html.erb
<section id="content">
  <!--start page contents-->

  <!-- area: clock readout -->
  <div class="checkin-counter">
    <%=  image_tag "webapp/clock/dash.png", :id => "dig1" %>
    <%=  image_tag "webapp/clock/dash.png", :id => "dig2" %>
    <%=  image_tag "webapp/clock/dash.png", :id => "dig3" %>
    <%=  image_tag "webapp/clock/dash.png", :id => "dig4" %>
  </div>




  <!-- area: main -->
  <div id="whole" class="Main ColWhole">
    <div class="checkin-numpad">
      <form name="pin_pad">
        <input type="button" onclick="numKeys(1)" class="nbutton n1"/>
        <input type="button" onclick="numKeys(2)" class="nbutton n2"/>
        <input type="button" onclick="numKeys(3)" class="nbutton n3"/>
        <br />
        <input type="button" onclick="numKeys(4)" class="nbutton n4"/>
        <input type="button" onclick="numKeys(5)" class="nbutton n5"/>
        <input type="button" onclick="numKeys(6)" class="nbutton n6"/>
        <br />
        <input type="button" onclick="numKeys(7)" class="nbutton n7"/>
        <input type="button" onclick="numKeys(8)" class="nbutton n8"/>
        <input type="button" onclick="numKeys(9)" class="nbutton n9"/>
        <br />
        <input type="button" onclick="backspace()" class="nbutton n10"/>
        <input type="button" onclick="numKeys(0)" class="nbutton n11"/>
        <input type="button" onclick="clearPin()" class="nbutton n12">
        <br />
      </form>

      <div class="clr"></div>

    </div>
    <div class="clr"></div>
  </div>

  <div class="clr"></div>

  <!--end page contents-->
</section>
<div class="clr"></div>
<footer class="footer" id="footer">
  <div>
    <%= link_to image_tag("webapp/buttons/deactivate.jpg"), cancel_alert_organization_outstanding_path(@organization, @outstanding) %>

  </div>
  </footer>

app/views/outstandings/show.html.erb
<section id="content">
  <!--start page contents-->
  <div class="title-countdown">&nbsp;</div>
  <div class="title-alert">&nbsp;</div>

  <!-- area: clock readout -->
  <div class="countdown-counter">
    <%=  image_tag "webapp/clock/0.png", :id => "dig1" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig2" %>
    <%=  image_tag "webapp/clock/colon.png", :class => "clock-colon" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig3" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig4" %>
    <%=  image_tag "webapp/clock/colon.png", :class => "clock-colon" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig5" %>
    <%=  image_tag "webapp/clock/0.png", :id => "dig6" %>
  </div>





  <div class="clr"></div>

  <!--end page contents-->
</section>
<div class="clr"></div>
<footer class="footer" id="footer">


  <div><%= link_to image_tag("webapp/buttons/deactivate.jpg"), pin_cancel_organization_outstanding_path(@organization, @outstanding) %> </div>
  <br />
  <br />
  <div><%= link_to image_tag("webapp/buttons/panic.jpg"), panic_alert_organization_outstanding_path(@organization, @outstanding) %>  </div>





</footer>