config/routes.rb
Auth::Application.routes.draw do
  resources :global_settings
  resources :sessions do
    member do
      get 'new_admin'
      #get 'admin_destroy'
      #get 'create_admin'
    end
  end
  resources :password_resets

  resources :organizations do
    collection do
      get 'index_active_orgs'
    end
    member do
      get 'deactivate_account'
    end
    resources :settings
    resources :settings
    resources :users do
      member do
        get 'admin_login'
        get 'new_admin'
        get 'set_pin'
        get 'save_pin'
      end
    end
    resources :outstandings do
      collection do
        get 'expired_index'
      end
      member do
        get 'cancel_alert'
        get 'panic_alert'
        get 'sent_alert'
        get 'pin_cancel'
      end
      resources :checkins
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  get "org_index" => "organizations#index_active_orgs", :as => "org_index"
  #get "deactivate_account" => "organizations#deactivate_account", :as => "deactivate_account"
  #resources :organizations, :member => {:organizations => :index_active_orgs}
  #resources :organizations, :member => {:organizations => :deactivate_account}

  get "pin_cancel" => "organizations#outstandings#pin_cancel", :as => "pin_cancel"
  get "cancel_alert" => "organizations#outstandings#cancel_alert", :as => "cancel_alert"
  get "panic_alert" => "organizations#outstandings#panic_alert", :as => "panic_alert"
  get "sent_alert" => "organizations#outstandings#sent_alert", :as => "sent_alert"
  get "expired" => "organizations#outstandings#expired_index", :as => "expired"
  get "active" => "organizations#outstandings#index", :as => "active"
  get "new_alert" => "organizations#outstandings#new", :as => "new_alert"
  #resources :outstandings, :member => {:outstandings => :expired_index}
  #resources :outstandings, :member => {:outstandings => :cancel_alert}
  #resources :outstandings, :member => {:outstandings => :pin_cancel}
  #resources :outstandings, :member => {:outstandings => :panic_alert}
  #resources :outstandings, :member => {:outstandings => :sent_alert}
  #resources :outstandings, :member => {:outstandings => :index}


  get "admin_login" => "sessions#create", :as => "admin_login"
  get "admin" => "sessions#new_admin", :as => "admin"
  get "admin_logout" => "sessions#destroy", :as => "admin_logout"
  #get "admin_login" => "sessions#create_admin", :as => "admin_login"
  #get "admin" => "sessions#new_admin", :as => "admin"
  #get "admin_logout" => "sessions#admin_destroy", :as => "admin_logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "organizations#users#new", :as => "signup"
  get "set_pin" => "organizations#users#set_pin", :as => "set_pin"
  get "save_pin" => "organizations#users#save_pin", :as => "save_pin"
  #resources :users, :member => {:users => :set_pin}
  #resources :users, :member => {:users => :save_pin}
  #resources :sessions, :member => {:sessions => :new_admin}
  #resources :sessions, :member => {:sessions => :admin_destroy}
  #resources :sessions, :member => {:sessions => :create_admin}

  #if mobile_user?
    root :to => "sessions#new"
  #else
  #  root :to => "sessinons#new_admin"
  #end




end

app/models/setting.rb
class Setting < ActiveRecord::Base
  attr_accessible :green_hours, :green_mins, :yellow_hours, :yellow_mins, :red_hours, :red_mins, :reminder_sms,
                  :reminder_sms_hours, :reminder_sms_mins, :logo_url, :comp_name, :alert_emails, :alert_smss,
                  :history_hours, :time_zone, :user_id, :organization_id, :dashboard_logo, :startup_image, :icon, :delete_logo

  belongs_to :organization

  has_attached_file :dashboard_logo, :styles => { :medium => "300x90>"},
                    :url => "/assets/paperclip/settings/:id/dashboard_logo/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/paperclip/settings/:id/dashboard_logo/:style/:basename.:extension"
  has_attached_file :startup_image, :styles => { :medium => "320x460"},
                    :url => "/assets/paperclip/settings/:id/startup_image/:style/startup.png",
                    :path => ":rails_root/public/assets/paperclip/settings/:id/startup_image/:style/startup.png"
  has_attached_file :icon, :styles => { :small => "57x57", :medium => "72x72", :large => "114x114"},
                    :url => "/assets/paperclip/settings/:id/icon/:style/apple-touch-icon-precomposed.png",
                    :path => ":rails_root/public/assets/paperclip/settings/:id/icon/:style/apple-touch-icon-precomposed.png"

  validates_attachment :dashboard_logo, :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  validates_attachment :startup_image, :content_type => { :content_type => ["image/png"] }
  validates_attachment :icon, :content_type => { :content_type => ["image/png"] }

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :get_org
  before_filter :check_org, :only => :edit

  def get_org
    @organization = Organization.find(params[:organization_id])
  end

  def check_org
    if current_user.super_user != true
      @proper_org = Organization.find(current_user.organization)
    end

    if current_user.admin == false && current_user.super_user == false
      redirect_to new_organization_outstanding_path(@proper_org)
    elsif current_user.organization_id != @organization.id && current_user.super_user == false
      redirect_to organization_path(@proper_org)
    end
  end

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @settings }
    end
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
    @setting = Setting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/new
  # GET /settings/new.json
  def new
    @setting = Setting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @setting }
    end
  end

  # GET /settings/1/edit
  def edit
    @setting = @organization.setting
    @admin_users = @organization.users.find(:all, :conditions => ['admin = true'])
    render :layout => 'application_dashboard'
  end

  # POST /settings        :controller => 'outstandings', :action => 'new'
  # POST /settings.json
  def create
    @setting = @organization.setting.new(params[:setting])

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render json: @setting, status: :created, location: @setting }
      else
        format.html { render action: "new" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /settings/1
  # PUT /settings/1.json
  def update
    @setting = Setting.find(params[:id])


    respond_to do |format|
      if @setting.update_attributes(params[:setting])
        if @setting.delete_logo == true
          @setting.dashboard_logo = nil
          @setting.save
        end
        format.html { redirect_to edit_organization_setting_path(@organization, @setting), notice: 'Settings were successfully saved.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting = Setting.find(params[:id])
    @setting.destroy

    respond_to do |format|
      format.html { redirect_to settings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/_form.html.erb
<%= form_for([@organization, @setting], :html => { :multipart => true }) do |f| %>
    <div class="Col1">
      <!--
      <div class="MenuItem"><div class="MenuItemLabel">Color scheme for active alerts:</div>
        <select id="UF-colorscheme">
          <option value="volvo">Default</option>
          <option value="saab">Color Scheme 1</option>
          <option value="mercedes">Color Scheme 2</option>
          <option value="audi">Color Scheme 3</option>
        </select>
      </div>
       -->
      <div class="MenuItem"><div class="MenuItemLabel">Duration of Green Light before countdown:</div> <%= f.number_field :green_hours, {:maxlength => "2",  :size => "4"} %>:<%= f.number_field :green_mins, {:maxlength => "2",  :size => "4"} %> (hours:mins) </div>
      <div class="MenuItem"><div class="MenuItemLabel">Duration of Yellow Light before countdown:</div> <%= f.number_field :yellow_hours, {:maxlength => "2",  :size => "4"} %>:<%= f.number_field :yellow_mins, {:maxlength => "2",  :size => "4"} %> (hours:mins) </div>
      <div class="MenuItem"><div class="MenuItemLabel">Duration of Red Light before countdown:</div> <%= f.number_field :red_hours, {:maxlength => "2",  :size => "4"} %>:<%= f.number_field :red_mins, {:maxlength => "2",  :size => "4"} %> (hours:mins) </div>

      <div class="MenuItem"><div class="MenuItemLabel">Reminder SMS:</div>    <%= f.select :reminder_sms, [["Yes",true],["No",false]]  %></div>

      <div class="MenuItem"><div class="MenuItemLabel">When should SMS reminder be sent?</div>   <%= f.number_field :reminder_sms_hours, {:maxlength => "2",  :size => "4"} %>:<%= f.number_field :reminder_sms_mins, {:maxlength => "2",  :size => "4"} %> (hours:mins) remaining </div>
      <div class="MenuItem"><div class="MenuItemLabel">Time Zone:</div> <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones %></div>
    </div>

    <div class="Col2">
      <div class="MenuItem">
        <div class="MenuItemLabel">
        Company Logo:<br />
        (300 x 90 GIF/JPG/PNG)
        </div><%= @organization.setting.dashboard_logo_file_name %><br />
        <%= f.file_field :dashboard_logo %><br />
        <%= f.check_box :delete_logo, {checked: false} %> Restore System Default
      </div>

      <div class="MenuItem"><div class="MenuItemLabel">Primary Admin User:</div><%= collection_select(:setting, :user_id, @admin_users, :id, :name_last) %> </div>
      <div class="MenuItem"><div class="MenuItemLabel">E-mail address for Alerts:</div><%= f.text_field :alert_emails %></div>
      <div class="MenuItem"><div class="MenuItemLabel">SMS number for Alerts:</div><%= f.text_field :alert_smss %></div>
      <div class="MenuItem"><div class="MenuItemLabel">Show recent items for past:</div><%= f.number_field :history_hours %> hrs</div>

      <div class="MenuItem">
        <%= flash[:notice] %><%= flash[:error] %> <br />
        <%= f.submit "Save Settings" %> <!--<input type="reset" value="Reset" />  -->

    </div>

    <div class="clr"></div>

    </div>
<% end %>

app/views/settings/edit.html.erb
<div class="clr"></div>
<!-- area: main -->
<div id="whole" class="Main ColWhole">

  <!-- UI: Settings Menu -->
  <h2>Settings</h2>
  <div class="SettingsMenu">


        <%= render 'form' %>



  <!-- End UI: Settings Menu -->
   </div>
</div>

app/views/settings/index.html.erb
<h1>Listing settings</h1>

<table>
  <tr>
    <th>Green hours</th>
    <th>Green mins</th>
    <th>Yellow hours</th>
    <th>Yellow mins</th>
    <th>Red hours</th>
    <th>Red mins</th>
    <th>Reminder sms</th>
    <th>Reminder sms hours</th>
    <th>Reminder sms mins</th>
    <th>Logo url</th>
    <th>Comp name</th>
    <th>Alert emails</th>
    <th>Alert smss</th>
    <th>History hours</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @settings.each do |setting| %>
  <tr>
    <td><%= setting.green_hours %></td>
    <td><%= setting.green_mins %></td>
    <td><%= setting.yellow_hours %></td>
    <td><%= setting.yellow_mins %></td>
    <td><%= setting.red_hours %></td>
    <td><%= setting.red_mins %></td>
    <td><%= setting.reminder_sms %></td>
    <td><%= setting.reminder_sms_hours %></td>
    <td><%= setting.reminder_sms_mins %></td>
    <td><%= setting.logo_url %></td>
    <td><%= setting.comp_name %></td>
    <td><%= setting.alert_emails %></td>
    <td><%= setting.alert_smss %></td>
    <td><%= setting.history_hours %></td>
    <td><%= link_to 'Show', setting %></td>
    <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
    <td><%= link_to 'Destroy', setting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New setting</h1>

<%= render 'form' %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Green hours:</b>
  <%= @setting.green_hours %>
</p>

<p>
  <b>Green mins:</b>
  <%= @setting.green_mins %>
</p>

<p>
  <b>Yellow hours:</b>
  <%= @setting.yellow_hours %>
</p>

<p>
  <b>Yellow mins:</b>
  <%= @setting.yellow_mins %>
</p>

<p>
  <b>Red hours:</b>
  <%= @setting.red_hours %>
</p>

<p>
  <b>Red mins:</b>
  <%= @setting.red_mins %>
</p>

<p>
  <b>Reminder sms:</b>
  <%= @setting.reminder_sms %>
</p>

<p>
  <b>Reminder sms hours:</b>
  <%= @setting.reminder_sms_hours %>
</p>

<p>
  <b>Reminder sms mins:</b>
  <%= @setting.reminder_sms_mins %>
</p>

<p>
  <b>Logo url:</b>
  <%= @setting.logo_url %>
</p>

<p>
  <b>Comp name:</b>
  <%= @setting.comp_name %>
</p>

<p>
  <b>Alert emails:</b>
  <%= @setting.alert_emails %>
</p>

<p>
  <b>Alert smss:</b>
  <%= @setting.alert_smss %>
</p>

<p>
  <b>History hours:</b>
  <%= @setting.history_hours %>
</p>


<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>