config/routes.rb
Auth::Application.routes.draw do
  resources :global_settings
  resources :sessions do
    member do
      get 'new_admin'
      #get 'admin_destroy'
      #get 'create_admin'
    end
  end
  resources :password_resets

  resources :organizations do
    collection do
      get 'index_active_orgs'
    end
    member do
      get 'deactivate_account'
    end
    resources :settings
    resources :settings
    resources :users do
      member do
        get 'admin_login'
        get 'new_admin'
        get 'set_pin'
        get 'save_pin'
      end
    end
    resources :outstandings do
      collection do
        get 'expired_index'
      end
      member do
        get 'cancel_alert'
        get 'panic_alert'
        get 'sent_alert'
        get 'pin_cancel'
      end
      resources :checkins
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  get "org_index" => "organizations#index_active_orgs", :as => "org_index"
  #get "deactivate_account" => "organizations#deactivate_account", :as => "deactivate_account"
  #resources :organizations, :member => {:organizations => :index_active_orgs}
  #resources :organizations, :member => {:organizations => :deactivate_account}

  get "pin_cancel" => "organizations#outstandings#pin_cancel", :as => "pin_cancel"
  get "cancel_alert" => "organizations#outstandings#cancel_alert", :as => "cancel_alert"
  get "panic_alert" => "organizations#outstandings#panic_alert", :as => "panic_alert"
  get "sent_alert" => "organizations#outstandings#sent_alert", :as => "sent_alert"
  get "expired" => "organizations#outstandings#expired_index", :as => "expired"
  get "active" => "organizations#outstandings#index", :as => "active"
  get "new_alert" => "organizations#outstandings#new", :as => "new_alert"
  #resources :outstandings, :member => {:outstandings => :expired_index}
  #resources :outstandings, :member => {:outstandings => :cancel_alert}
  #resources :outstandings, :member => {:outstandings => :pin_cancel}
  #resources :outstandings, :member => {:outstandings => :panic_alert}
  #resources :outstandings, :member => {:outstandings => :sent_alert}
  #resources :outstandings, :member => {:outstandings => :index}


  get "admin_login" => "sessions#create", :as => "admin_login"
  get "admin" => "sessions#new_admin", :as => "admin"
  get "admin_logout" => "sessions#destroy", :as => "admin_logout"
  #get "admin_login" => "sessions#create_admin", :as => "admin_login"
  #get "admin" => "sessions#new_admin", :as => "admin"
  #get "admin_logout" => "sessions#admin_destroy", :as => "admin_logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "organizations#users#new", :as => "signup"
  get "set_pin" => "organizations#users#set_pin", :as => "set_pin"
  get "save_pin" => "organizations#users#save_pin", :as => "save_pin"
  #resources :users, :member => {:users => :set_pin}
  #resources :users, :member => {:users => :save_pin}
  #resources :sessions, :member => {:sessions => :new_admin}
  #resources :sessions, :member => {:sessions => :admin_destroy}
  #resources :sessions, :member => {:sessions => :create_admin}

  #if mobile_user?
    root :to => "sessions#new"
  #else
  #  root :to => "sessinons#new_admin"
  #end




end

app/models/checkin.rb
class Checkin < ActiveRecord::Base
  attr_accessible :latitude, :longitude, :checkin_hours, :checkin_mins, :panic_deadline, :outstanding_id, :checkin_time
  belongs_to :outstanding

#  before_validation(:on => :create) do


#    self.updated_deadline = Time.now
#    self.updated_deadline = self.updated_deadline + self.checkin_hours.hours
#    self.updated_deadline = self.updated_deadline + self.checkin_mins.minutes

#    self.checkin_time = Time.now
#  end

end

app/controllers/checkins_controller.rb
class CheckinsController < ApplicationController
  # GET /checkins
  # GET /checkins.json
  def index
    @checkins = Checkin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @checkins }
    end
  end

  # GET /checkins/1
  # GET /checkins/1.json
  def show
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @checkin }
    end
  end

  # GET /checkins/new
  # GET /checkins/new.json
  def new
    @checkin = Checkin.new

    respond_to do |format|
      format.html { render :layout => 'application_loc'}
      format.json { render json: @checkin }
    end
  end

  # GET /checkins/1/edit
  def edit
    @checkin = Checkin.find(params[:id])
  end

  # POST /checkins
  # POST /checkins.json
  def create
    @checkin = Checkin.new(params[:checkin])

    respond_to do |format|
      if @checkin.save
        format.html { redirect_to @checkin, notice: 'Checkin was successfully created.' }
        format.json { render json: @checkin, status: :created, location: @checkin }
      else
        format.html { render action: "new" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /checkins/1
  # PUT /checkins/1.json
  def update
    @checkin = Checkin.find(params[:id])

    respond_to do |format|
      if @checkin.update_attributes(params[:checkin])
        format.html { redirect_to @checkin, notice: 'Checkin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @checkin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checkins/1
  # DELETE /checkins/1.json
  def destroy
    @checkin = Checkin.find(params[:id])
    @checkin.destroy

    respond_to do |format|
      format.html { redirect_to checkins_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/checkins_helper.rb
module CheckinsHelper
end

app/views/checkins/_form.html.erb
<%= form_for(@checkin) do |f| %>
  <% if @checkin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checkin.errors.count, "error") %> prohibited this checkin from being saved:</h2>

      <ul>
      <% @checkin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.select :checkin_hours, options_for_select(Array(0..99), 0)  %><%= f.label :checkin_hours %>
    <%= f.select :checkin_mins, options_for_select(Array(1..59), 30) %><%= f.label :checkin_mins %>
    <%= f.text_field :latitude %>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checkins/edit.html.erb
<h1>Editing checkin</h1>

<%= render 'form' %>

<%= link_to 'Show', @checkin %> |
<%= link_to 'Back', checkins_path %>

app/views/checkins/index.html.erb
<h1>Listing checkins</h1>

<table>
  <tr>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Checkin time</th>
    <th>Updated deadline</th>
    <th>Outstanding</th>
    <th>Checkin hours</th>
    <th>Checkin mins</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @checkins.each do |checkin| %>
  <tr>
    <td><%= checkin.latitude %></td>
    <td><%= checkin.longitude %></td>
    <td><%= checkin.checkin_time %></td>
    <td><%= checkin.updated_deadline %></td>
    <td><%= checkin.outstanding_id %></td>
    <td><%= checkin.checkin_hours %></td>
    <td><%= checkin.checkin_mins %></td>
    <td><%= link_to 'Show', checkin %></td>
    <td><%= link_to 'Edit', edit_checkin_path(checkin) %></td>
    <td><%= link_to 'Destroy', checkin, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Checkin', new_checkin_path %>

app/views/checkins/new.html.erb
<h1>New checkin</h1>

<%= render 'form' %>

<%= link_to 'Back', checkins_path %>

app/views/checkins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @checkin.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @checkin.longitude %>
</p>

<p>
  <b>Checkin time:</b>
  <%= @checkin.checkin_time %>
</p>

<p>
  <b>Updated deadline:</b>
  <%= @checkin.updated_deadline %>
</p>

<p>
  <b>Outstanding:</b>
  <%= @checkin.outstanding_id %>
</p>

<p>
  <b>Checkin hours:</b>
  <%= @checkin.checkin_hours %>
</p>

<p>
  <b>Checkin mins:</b>
  <%= @checkin.checkin_mins %>
</p>


<%= link_to 'Edit', edit_checkin_path(@checkin) %> |
<%= link_to 'Back', checkins_path %>