config/routes.rb
Auth::Application.routes.draw do
  resources :global_settings
  resources :sessions do
    member do
      get 'new_admin'
      #get 'admin_destroy'
      #get 'create_admin'
    end
  end
  resources :password_resets

  resources :organizations do
    collection do
      get 'index_active_orgs'
    end
    member do
      get 'deactivate_account'
    end
    resources :settings
    resources :settings
    resources :users do
      member do
        get 'admin_login'
        get 'new_admin'
        get 'set_pin'
        get 'save_pin'
      end
    end
    resources :outstandings do
      collection do
        get 'expired_index'
      end
      member do
        get 'cancel_alert'
        get 'panic_alert'
        get 'sent_alert'
        get 'pin_cancel'
      end
      resources :checkins
    end
  end

  match "/delayed_job" => DelayedJobWeb, :anchor => false

  get "org_index" => "organizations#index_active_orgs", :as => "org_index"
  #get "deactivate_account" => "organizations#deactivate_account", :as => "deactivate_account"
  #resources :organizations, :member => {:organizations => :index_active_orgs}
  #resources :organizations, :member => {:organizations => :deactivate_account}

  get "pin_cancel" => "organizations#outstandings#pin_cancel", :as => "pin_cancel"
  get "cancel_alert" => "organizations#outstandings#cancel_alert", :as => "cancel_alert"
  get "panic_alert" => "organizations#outstandings#panic_alert", :as => "panic_alert"
  get "sent_alert" => "organizations#outstandings#sent_alert", :as => "sent_alert"
  get "expired" => "organizations#outstandings#expired_index", :as => "expired"
  get "active" => "organizations#outstandings#index", :as => "active"
  get "new_alert" => "organizations#outstandings#new", :as => "new_alert"
  #resources :outstandings, :member => {:outstandings => :expired_index}
  #resources :outstandings, :member => {:outstandings => :cancel_alert}
  #resources :outstandings, :member => {:outstandings => :pin_cancel}
  #resources :outstandings, :member => {:outstandings => :panic_alert}
  #resources :outstandings, :member => {:outstandings => :sent_alert}
  #resources :outstandings, :member => {:outstandings => :index}


  get "admin_login" => "sessions#create", :as => "admin_login"
  get "admin" => "sessions#new_admin", :as => "admin"
  get "admin_logout" => "sessions#destroy", :as => "admin_logout"
  #get "admin_login" => "sessions#create_admin", :as => "admin_login"
  #get "admin" => "sessions#new_admin", :as => "admin"
  #get "admin_logout" => "sessions#admin_destroy", :as => "admin_logout"
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "organizations#users#new", :as => "signup"
  get "set_pin" => "organizations#users#set_pin", :as => "set_pin"
  get "save_pin" => "organizations#users#save_pin", :as => "save_pin"
  #resources :users, :member => {:users => :set_pin}
  #resources :users, :member => {:users => :save_pin}
  #resources :sessions, :member => {:sessions => :new_admin}
  #resources :sessions, :member => {:sessions => :admin_destroy}
  #resources :sessions, :member => {:sessions => :create_admin}

  #if mobile_user?
    root :to => "sessions#new"
  #else
  #  root :to => "sessinons#new_admin"
  #end




end

app/views/layouts/_apple_webapp.html.erb
<link rel="apple-touch-icon" href="apple-touch-icon-precomposed.png" />
<link rel="apple-touch-icon" sizes="72x72" href="apple-touch-icon-72x72-precomposed.png" />
<link rel="apple-touch-icon" sizes="114x114" href="apple-touch-icon-114x114-precomposed.png" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<link rel="apple-touch-startup-image" href="startup.png">

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'style_admin', :media => 'screen' %>
<%= stylesheet_link_tag 'style_mobile', :media => 'handheld, only screen and (max-device-width: 480px)' %>

app/views/layouts/alert.html.erb
<!DOCTYPE HTML>
<html>
    <head>
    <title>Guardian Trace - alert</title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
      <%= stylesheet_link_tag 'style_mobile'%>
    </head>
    <body class="GTpage page-alert">
    <div class="inner">
  
       <header class="header" id="header">
<a href="logout"><div class="topX"></div></a>
       
       
       </header>

       <section id="content">
       <!--start page contents-->


       


       
       <!--end page contents-->
       </section>
       <div class="clr"></div>
       <footer class="footer" id="footer">
         
        <%=  yield %>
       
       
       </footer>
     
    </div>
    <div class="clr"></div>
      <div class="Copyright">&copy; 2012 Austin Themes. Website for preview only. All rights reserved until final payment.</div>
    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth Example</title>
  <%= stylesheet_link_tag    "application", :media => 'screen' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
    <div id="user_nav">
      <b>Time Now:</b> <%= Time.now %><br />
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "log in", login_path %>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application_dashboard.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace - Dashboard</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= stylesheet_link_tag 'style_admin'%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    function add_pin() {
        var the_pin = document.getElementById("password_field").value;
        document.getElementById("pin_field").value = the_pin;

    }
  </script>
</head>
<body class="GTpage">
<div class="inner">

  <header class="header" id="header">

    <div class="headerLeft"><a href="#">
      <% unless @organization.setting.dashboard_logo_file_name.nil? %>
        <%=  image_tag @organization.setting.dashboard_logo(:medium), :id => "logo", :class => "logo" %>
      <% else %>
          <%=  image_tag "images/logo.jpg", :id => "logo", :class => "logo" %>
      <% end %>
    </a></div>
    <div class="headerRight"><div class="headerByline"><a href="#">Help</a> |
      <% if current_user %>
          <% if current_user.super_user == true %>
              <%= link_to "Super Dashboard |", organizations_path %>
          <% end %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log out", admin_logout_path %>
      <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", admin_login_path %>
      <% end %></div></div>

    <div class="topmenu">
      <%= link_to image_tag("images/Nav1.jpg"), organization_outstandings_path(@organization), {:class => "MenuItem1 MenuItem"} %>
      <%= link_to image_tag("images/Nav2.jpg"), expired_index_organization_outstandings_path(@organization), {:class => "MenuItem2 MenuItem"} %>
      <%= link_to image_tag("images/Nav3.jpg"), organization_users_path(@organization), {:class => "MenuItem3 MenuItem"} %>
      <%= link_to image_tag("images/Nav4.jpg"), edit_organization_setting_path(@organization, @organization.setting), {:class => "MenuItem4 MenuItem"} %>

    </div>
  </header>
  <section id="content">
    <!--start page contents-->

    <%=  yield %>





    <!--end page contents-->
  </section>
  <div class="clr"></div>
  <footer class="footer" id="footer"><a href="#">Powered by BAYTAN LABS</a></footer>
  <div class="Copyright"></div>
</div>
</body>
</html>

app/views/layouts/application_dashboard_orgs.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace - Dashboard</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= stylesheet_link_tag 'style_admin'%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    function add_pin() {
        var the_pin = document.getElementById("password_field").value;
        document.getElementById("pin_field").value = the_pin;

    }
  </script>
</head>
<body class="GTpage">
<div class="inner">

  <header class="header" id="header">

    <div class="headerLeft"><a href="#"><%=  image_tag "images/logo.jpg", :id => "logo", :class => "logo" %></a></div>
    <div class="headerRight"><div class="headerByline"><a href="#">Help</a> |
      <% if current_user %>
          <% if current_user.super_user == true %>
              <%= link_to "Super Dashboard |", organizations_path %>
          <% end %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log out", admin_logout_path %>
      <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", admin_login_path %>
      <% end %></div></div>

    <div class="topmenu">
      <%= link_to image_tag("images/org_level/Nav1.jpg"), organizations_path, {:class => " MenuItem"} %>
      <%= link_to image_tag("images/org_level/Nav2.jpg"), index_active_orgs_organizations_path, {:class => " MenuItem"} %>


    </div>
  </header>
  <section id="content">
    <!--start page contents-->

    <%=  yield %>





    <!--end page contents-->
  </section>
  <div class="clr"></div>
  <footer class="footer" id="footer"><a href="#">Powered by BAYTAN LABS</a></footer>
  <div class="Copyright"></div>
</div>
</body>
</html>

app/views/layouts/application_loc.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auth Example</title>
  <%= stylesheet_link_tag    "application", :media => 'screen' %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "geolocation/geolocation" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] %>">
  <div id="container">
    <div id="user_nav">
      <b>Time Now:</b> <%= Time.now %><br />
      <% if current_user %>
        Logged in as <%= current_user.email %>.
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Sign up", signup_path %> or
        <%= link_to "log in", login_path %>
      <% end %>
    </div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application_mobile.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'style_mobile' %>
  <%= csrf_meta_tag %>
  <%= render "layouts/apple_webapp" %>
</head>
<body class="GTpage page-login" onload="areCookiesEnabled()">
<div class="inner">

  <header class="header" id="header">
    <div class="topX">
      <%= link_to image_tag("webapp/X.png"), logout_path %>
    </div>


  </header>

  <%= yield %>


  <div class="clr"></div>
</div>
<div class="clr"></div>
<div class="Copyright"></div>
</body>
</html>

app/views/layouts/application_mobile_loc.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'style_mobile'%>

  <%= render "layouts/apple_webapp" %>
  <script type="text/javascript">

      var saved_pin = "0000";
      var entered_pin = "";
      var entered_hours = "00";
      var entered_mins = "00";
      var pin_count = 0;

      var img1 = null;
      var img2 = null;
      var img3 = null;
      var img4 = null;

      function inits() {
          loadGeoloc();

          if(img1===null) img1  =  document.getElementById("dig1");
          if(img2===null) img2  =  document.getElementById("dig2");
          if(img3===null) img3  =  document.getElementById("dig3");
          if(img4===null) img4  =  document.getElementById("dig4");

          document.getElementById("hours_field").value = 0;
          document.getElementById("mins_field").value = 30;
      }

      function loadGeoloc(){
          if (navigator.geolocation) {
              var timeoutVal = 10 * 1000 * 1000;
              navigator.geolocation.getCurrentPosition(
                      displayPosition,
                      displayError,
                      { enableHighAccuracy: true, timeout: timeoutVal, maximumAge: 0 }
              );
          }
          else {
              alert("Geolocation is not supported by this browser");
          }
      }

      function displayPosition(position) {
          populateInputs(position.coords.latitude,position.coords.longitude);

      }

      function displayError(error) {
          var errors = {
              1: 'Permission denied',
              2: 'Position unavailable',
              3: 'Request timeout'
          };
          alert("Error: " + errors[error.code]);
      }

      function populateInputs(lat,lng) {
          if (document.forms[0].outstanding_latitude) {
              document.getElementById("latitude").value=lat;
              document.getElementById("longitude").value=lng;
          }
          else {
              document.getElementById("latitude").value=lat;
              document.getElementById("longitude").value=lng;
          }
      }



      function checkPin() {
          n = entered_pin.length;
          entered_hours = "";
          entered_mins = "";

          switch(n) {
              case 0:
                  document.getElementById("hours_field").value = 0;
                  document.getElementById("mins_field").value = 0;
                  break;
              case 1:
                  document.getElementById("hours_field").value = entered_hours.concat(entered_pin.charAt(0), "0");
                  document.getElementById("mins_field").value = 0;
                  break;
              case 2:
                  document.getElementById("hours_field").value = entered_hours.concat(entered_pin.charAt(0), entered_pin.charAt(1));
                  document.getElementById("mins_field").value = 0;
                  break;
              case 3:
                  document.getElementById("hours_field").value = entered_hours.concat(entered_pin.charAt(0), entered_pin.charAt(1));
                  document.getElementById("mins_field").value = entered_mins.concat(entered_pin.charAt(2), "0");
                  break;
              case 4:
                  document.getElementById("hours_field").value = entered_hours.concat(entered_pin.charAt(0), entered_pin.charAt(1));
                  document.getElementById("mins_field").value = entered_mins.concat(entered_pin.charAt(2), entered_pin.charAt(3));;
                  break;
          }

      }

      function numKeys(n) {
          if (entered_pin.length < 4) {
              entered_pin = entered_pin + n.toString();
              selectDigit(n);
          }
           checkPin();
      }

      function backspace() {
          n = entered_pin.length;
          if (n > 0) {
              entered_pin = entered_pin.substring(0,(n-1));
              switch (entered_pin.length) {
                  case 0:
                      img1.src = numToImage(10);
                      break;
                  case 1:
                      img2.src = numToImage(10);
                      break;
                  case 2:
                      img3.src = numToImage(10);
                      break;
                  case 3:
                      img4.src = numToImage(10);
                      break;
              }
              checkPin();
          }
      }

      function selectImage() {
          img1.src = "<%= image_path("webapp/clock/1.png") %>";
      }

      function clearPin() {
          entered_pin = "";
          entered_hours = "";
          entered_mins = "";
          img1.src = numToImage(10);
          img2.src = numToImage(10);
          img3.src = numToImage(10);
          img4.src = numToImage(10);
          document.getElementById("hours_field").value = 0;
          document.getElementById("mins_field").value = 0;
      }

      function selectDigit(n) {
          switch (entered_pin.length-1) {
              case 0:
                  img1.src = numToImage(n);
                  break;
              case 1:
                  img2.src = numToImage(n);
                  break;
              case 2:
                  img3.src = numToImage(n);
                  break;
              case 3:
                  img4.src = numToImage(n);
                  break;
          }
      }


      function numToImage(n) {
          var image;
          switch(n) {
              case 0:
                  image = "<%= image_path("webapp/clock/0.png") %>";
                  break;
              case 1:
                  image = "<%= image_path("webapp/clock/1.png") %>";
                  break;
              case 2:
                  image = "<%= image_path("webapp/clock/2.png") %>";
                  break;
              case 3:
                  image = "<%= image_path("webapp/clock/3.png") %>";
                  break;
              case 4:
                  image = "<%= image_path("webapp/clock/4.png") %>";
                  break;
              case 5:
                  image = "<%= image_path("webapp/clock/5.png") %>";
                  break;
              case 6:
                  image = "<%= image_path("webapp/clock/6.png") %>";
                  break;
              case 7:
                  image = "<%= image_path("webapp/clock/7.png") %>";
                  break;
              case 8:
                  image = "<%= image_path("webapp/clock/8.png") %>";
                  break;
              case 9:
                  image = "<%= image_path("webapp/clock/9.png") %>";
                  break;
              case 10:
                  image = "<%= image_path("webapp/clock/dash.png") %>";
          }
          return image;
      }

      function play(){
          try{
              if(img1===null) img1  =  document.getElementById("dig1");
              if(img2===null) img2  =  document.getElementById("dig2");
              if(img3===null) img3  =  document.getElementById("dig3");
              if(img4===null) img4  =  document.getElementById("dig4");

              t = setTimeout('play()',1000);
          }catch(oEx){
              alert(oEx);
          }
      }

  </script>
</head>
<body class="GTpage page-checkin" onload="inits()">
<div class="inner">

  <header class="header" id="header">
 <div class="topX">
    <%= link_to image_tag("webapp/X.png"), logout_path %>
 </div>
    <%=  image_tag "webapp/title/countdown.jpg" %>


  </header>

  <%= yield %>

</div>

<div class="clr"></div>
<div class="Copyright"></div>
</body>
</html>

app/views/layouts/application_mobile_set_pin.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag 'style_mobile'%>
  <%= render "layouts/apple_webapp" %>
  <script type="text/javascript">

        var saved_pin = "<%= current_user.pin%>";
        var entered_pin = "";
        var pin_count = 0;

        var img1 = null;
        var img2 = null;
        var img3 = null;
        var img4 = null;

        function inits() {

        if(img1===null) img1  =  document.getElementById("dig1");
        if(img2===null) img2  =  document.getElementById("dig2");
        if(img3===null) img3  =  document.getElementById("dig3");
        if(img4===null) img4  =  document.getElementById("dig4");
        }

        function add_pin() {
            var the_pin = document.getElementById("password_field").value;
            document.getElementById("pin_field").value = entered_pin;
            document.getElementById("password_field").value = entered_pin;
            document.getElementById("conf_field").value = entered_pin;

        }




    function numKeys(n) {
        if (entered_pin.length < 4) {
                    entered_pin = entered_pin + n.toString();
                    selectDigit(n);
        }
        add_pin()
    }

    function backspace() {
        n = entered_pin.length;
        if (n > 0) {
            entered_pin = entered_pin.substring(0,(n-1));
            switch (entered_pin.length) {
                case 0:
                    img1.src = numToImage(10);
                    break;
                case 1:
                    img2.src = numToImage(10);
                    break;
                case 2:
                    img3.src = numToImage(10);
                    break;
                case 3:
                    img4.src = numToImage(10);
                    break;
            }
            add_pin()
        }
    }

    function selectImage() {
        img1.src = "<%= image_path("webapp/clock/1.png") %>";
    }

    function clearPin() {
        entered_pin = "";
        img1.src = numToImage(10);
        img2.src = numToImage(10);
        img3.src = numToImage(10);
        img4.src = numToImage(10);
        add_pin()
    }

    function selectDigit(n) {
        switch (entered_pin.length-1) {
            case 0:
                img1.src = numToImage(n);
                break;
            case 1:
                img2.src = numToImage(n);
                break;
            case 2:
                img3.src = numToImage(n);
                break;
            case 3:
                img4.src = numToImage(n);
                break;
        }
    }


    function numToImage(n) {
        var image;
        switch(n) {
            case 0:
                image = "<%= image_path("webapp/clock/0.png") %>";
                break;
            case 1:
                image = "<%= image_path("webapp/clock/1.png") %>";
                break;
            case 2:
                image = "<%= image_path("webapp/clock/2.png") %>";
                break;
            case 3:
                image = "<%= image_path("webapp/clock/3.png") %>";
                break;
            case 4:
                image = "<%= image_path("webapp/clock/4.png") %>";
                break;
            case 5:
                image = "<%= image_path("webapp/clock/5.png") %>";
                break;
            case 6:
                image = "<%= image_path("webapp/clock/6.png") %>";
                break;
            case 7:
                image = "<%= image_path("webapp/clock/7.png") %>";
                break;
            case 8:
                image = "<%= image_path("webapp/clock/8.png") %>";
                break;
            case 9:
                image = "<%= image_path("webapp/clock/9.png") %>";
                break;
            case 10:
                image = "<%= image_path("webapp/clock/dash.png") %>";
        }
        return image;
    }

    function play(){
        try{
            if(img1===null) img1  =  document.getElementById("dig1");
            if(img2===null) img2  =  document.getElementById("dig2");
            if(img3===null) img3  =  document.getElementById("dig3");
            if(img4===null) img4  =  document.getElementById("dig4");

            t = setTimeout('play()',1000);
        }catch(oEx){
            alert(oEx);
        }
    }

  </script>
</head>
<body class="GTpage page-checkin" onload="inits()">
<div class="inner">

  <header class="header" id="header">
    <div class="topX">
    <%= link_to image_tag("webapp/X.png"), logout_path %>
        </div>


  </header>

  <section id="content">
    <!--start page contents-->

    <!-- area: clock readout -->
    Choose New PIN:
    <div class="checkin-counter">
      <%=  image_tag "webapp/clock/dash.png", :id => "dig1" %>
      <%=  image_tag "webapp/clock/dash.png", :id => "dig2" %>
      <%=  image_tag "webapp/clock/dash.png", :id => "dig3" %>
      <%=  image_tag "webapp/clock/dash.png", :id => "dig4" %>
    </div>




    <!-- area: main -->
    <div id="whole" class="Main ColWhole">
      <div class="checkin-numpad">
        <form name="pin_pad">
          <input type="button" onclick="numKeys(1)" class="nbutton n1"/>
          <input type="button" onclick="numKeys(2)" class="nbutton n2"/>
          <input type="button" onclick="numKeys(3)" class="nbutton n3"/>
          <br />
          <input type="button" onclick="numKeys(4)" class="nbutton n4"/>
          <input type="button" onclick="numKeys(5)" class="nbutton n5"/>
          <input type="button" onclick="numKeys(6)" class="nbutton n6"/>
          <br />
          <input type="button" onclick="numKeys(7)" class="nbutton n7"/>
          <input type="button" onclick="numKeys(8)" class="nbutton n8"/>
          <input type="button" onclick="numKeys(9)" class="nbutton n9"/>
          <br />
          <input type="button" onclick="backspace()" class="nbutton n10"/>
          <input type="button" onclick="numKeys(0)" class="nbutton n11"/>
          <input type="button" onclick="clearPin()" class="nbutton n12">
          <br />
        </form>

        <div class="clr"></div>

      </div>
      <div class="clr"></div>
    </div>

    <div class="clr"></div>

    <!--end page contents-->
  </section>
  <div class="clr"></div>
  <footer class="footer" id="footer">
    <div>
      <%= form_for([@organization, @user])  do |f| %>
          <%= f.hidden_field :password, :id => "password_field", :onchange => "add_pin()" %>
          <%= f.hidden_field :password_confirmation, :id => "conf_field"  %>
          <%= f.hidden_field :pin, :id => "pin_field" %>
          <%= f.hidden_field :registered, :value => true %>

          <div class="button-activate"><%= f.submit "  ", :class => "button-activate-hidden" %></div>
      <% end %>

    </div>
  </footer>


</div>

<div class="clr"></div>
<div class="Copyright"></div>
</body>
</html>

app/views/layouts/dashboard_login.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace - Dashboard</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= stylesheet_link_tag 'style_admin'%>
  <style type="text/css">
      .loginScreen .Col2 .LogLeft{text-align: left;}
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    function add_pin() {
        var the_pin = document.getElementById("password_field").value;
        document.getElementById("pin_field").value = the_pin;

    }
  </script>
</head>
<body class="GTpage">
<div class="inner">

  <header class="header" id="header">

    <div class="headerLeft"><a href="#"><%=  image_tag "images/logo.jpg", :id => "logo", :class => "logo" %></a></div>
    <div class="headerRight"><div class="headerByline"><a href="#">Help</a> |
      <% if current_user %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log out", admin_logout_path %>
      <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", admin_login_path %>
      <% end %></div></div>


  </header>
  <section id="content">
    <!--start page contents-->

    <%=  yield %>





    <!--end page contents-->
  </section>
  <div class="clr"></div>
  <footer class="footer" id="footer"><a href="#">Powered by BAYTAN LABS</a></footer>
  <div class="Copyright"></div>
</div>
</body>
</html>

app/views/layouts/dashboard_set_pin.html.erb
<!DOCTYPE HTML>
<html>
<head>
  <title>Guardian Trace - Dashboard</title>
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <%= stylesheet_link_tag 'style_admin'%>
  <style type="text/css">
      .loginScreen .Col2 .LogLeft{float:left;width:50%;margin:0px;padding:4px;clear:both;font-size:22px;text-align:left; }
      .loginScreen .Col2 .LogRight{float:right;width:40%;margin:0px;padding:4px;}
  </style>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
    function add_pin() {
        var the_pin = document.getElementById("password_field").value;
        document.getElementById("pin_field").value = the_pin;

    }
  </script>
</head>
<body class="GTpage">
<div class="inner">

  <header class="header" id="header">

    <div class="headerLeft"><a href="#"><%=  image_tag "images/logo.jpg", :id => "logo", :class => "logo" %></a></div>
    <div class="headerRight"><div class="headerByline"><a href="#">Help</a> |
      <% if current_user %>
          <% if current_user.super_user == true %>
              <%= link_to "Super Dashboard |", organizations_path %>
          <% end %>
          Logged in as <%= current_user.email %>.
          <%= link_to "Log out", admin_logout_path %>
      <% else %>
          <%= link_to "Sign up", signup_path %> or
          <%= link_to "log in", admin_login_path %>
      <% end %></div></div>


  </header>
  <section id="content">
    <!--start page contents-->

    <!-- area: main -->



    <!-- area: main -->
    <div id="whole" class="Main ColWhole">

      <!-- UI: login -->

      <div class="loginScreen graybox">


        <div class="Col2">
          <h1>Login</h1><hr />
          <%= form_for([@organization, @user])  do |f| %>
              <div class="LogLeft"> <label>Pin</label></div>
              <div class="LogRight"> <%= f.password_field :password, :size => 4, :id => "password_field", :onchange => "add_pin()" %></div>
              <div class="clr"></div>
              <div class="LogLeft"> <label>Pin Confirmation</label></div>
              <div class="LogRight"> <%= f.password_field :password_confirmation, :size => 4, :id => "conf_field" %>
                <%= f.hidden_field :pin, :id => "pin_field" %></div>
              <div class="clr"></div>


              <hr />

              <%= f.submit "Save Pin", { :name => "1", :id => "LoginButton"} %>
          <% end %>

        </div>
        <div class="clr"></div>
      </div>

      <div class="clr"></div>




    </div>






    <!--end page contents-->
  </section>
  <div class="clr"></div>
  <footer class="footer" id="footer"><a href="#">Powered by BAYTAN LABS</a></footer>
  <div class="Copyright"></div>
</div>
</body>
</html>